// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StreetStatusAPI.Database;

#nullable disable

namespace StreetStatusAPI.Migrations
{
    [DbContext(typeof(StreetDbContext))]
    [Migration("20260415005210_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("StreetStatusAPI.Entities.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Calle")
                        .HasMaxLength(40)
                        .HasColumnType("TEXT")
                        .HasColumnName("Calle");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_date");

                    b.Property<DateTime>("LastModifiedDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_modified_date");

                    b.Property<string>("Name")
                        .HasMaxLength(40)
                        .HasColumnType("TEXT")
                        .HasColumnName("Ciudad");

                    b.Property<string>("UpdatedById")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_by_id");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_date");

                    b.Property<string>("ZipCode")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT")
                        .HasColumnName("Codigo_Postal");

                    b.HasKey("Id");

                    b.ToTable("locations");
                });

            modelBuilder.Entity("StreetStatusAPI.Entities.Street", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_date");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<DateTime>("LastModifiedDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_modified_date");

                    b.Property<DateTime>("LastRepairDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_repair_date");

                    b.Property<int>("LocationId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("location_id");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER")
                        .HasColumnName("status");

                    b.Property<string>("StreetName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("street_name");

                    b.Property<string>("UpdatedById")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_by_id");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_date");

                    b.HasKey("Id");

                    b.HasIndex("LocationId");

                    b.ToTable("streets");
                });

            modelBuilder.Entity("StreetStatusAPI.Entities.Street", b =>
                {
                    b.HasOne("StreetStatusAPI.Entities.Location", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Location");
                });
#pragma warning restore 612, 618
        }
    }
}
