// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StreetStatusAPI.Database;

#nullable disable

namespace StreetStatusAPI.Migrations
{
    [DbContext(typeof(StreetDbContext))]
    partial class StreetDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("StreetStatusAPI.Entities.Location", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT")
                        .HasColumnName("City");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_date");

                    b.Property<DateTime>("LastModifiedDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_modified_date");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT")
                        .HasColumnName("Street");

                    b.Property<string>("UpdatedById")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_by_id");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_date");

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT")
                        .HasColumnName("ZipCode");

                    b.HasKey("Id");

                    b.ToTable("locations");
                });

            modelBuilder.Entity("StreetStatusAPI.Entities.StreetEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_date");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<DateTime>("LastModifiedDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_modified_date");

                    b.Property<DateTime>("LastRepairDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_repair_date");

                    b.Property<string>("LocationId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("location_id");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER")
                        .HasColumnName("status");

                    b.Property<string>("StreetName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("street_name");

                    b.Property<string>("UpdatedById")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_by_id");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_date");

                    b.HasKey("Id");

                    b.HasIndex("LocationId");

                    b.ToTable("streets");
                });

            modelBuilder.Entity("StreetStatusAPI.Entities.StreetEntity", b =>
                {
                    b.HasOne("StreetStatusAPI.Entities.Location", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Location");
                });
#pragma warning restore 612, 618
        }
    }
}
